

CREATE TABLE exper (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) position, VARCHAR(128) company, VARCHAR(128) location, INT(8) start, INT(8) finish);
CREATE TABLE descript (INT id AUTO_INCREMENT PRIMARY KEY, INT exp_id, VARCHAR(512) phrase);

CREATE TABLE skills (INT id AUTO_INCREMENT PRIMARY KEY, INT header_id, INT skill_id);

CREATE TABLE skill_list (INT id AUTO_INCREMENT PRIMARY KEY, VARCHAR(128) name);

CREATE TABLE skill_queue (INT id AUTO_INCREMENT PRIMARY KEY, VARCHAR(128) name);

CREATE TABLE header (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name);

CREATE TABLE honors (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name, VARCHAR(256) desc, VARCHAR location(128), INT(8) acquired);

