CREATE TABLE users (INT id AUTO_INCREMENT PRIMARY KEY, VARCHAR(128) name, VARCHAR(256) email, VARCHAR(512) password, VARCHAR(40) salt);

CREATE TABLE address (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(512) address, VARCHAR(64) type);

CREATE TABLE website (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id,  VARCHAR(256) url, VARCHAR(64) type);

CREATE TABLE phone (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id,  VARCHAR(10) number, VARCHAR(64) type);

CREATE TABLE cover_letter (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, TEXT info);

CREATE TABLE reference (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name, VARCHAR(10) phone, VARCHAR(256) email, INT address_id, VARCHAR(512) company, INT account_id);

CREATE TABLE university (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name, VARCHAR(10) gpa, VARCHAR(256) degree, VARCHAR(512) desc, INT(8) start, INT(8) finish);

CREATE TABLE courses (INT id AUTO_INCREMENT PRIMARY KEY, INT uni_id, VARCHAR(128) course);

CREATE TABLE exper (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) position, VARCHAR(128) company, VARCHAR(128) location, INT(8) start, INT(8) finish);
CREATE TABLE descript (INT id AUTO_INCREMENT PRIMARY KEY, INT exp_id, VARCHAR(512) phrase);

CREATE TABLE skills (INT id AUTO_INCREMENT PRIMARY KEY, INT header_id, INT skill_id);

CREATE TABLE skill_list (INT id AUTO_INCREMENT PRIMARY KEY, VARCHAR(128) name);

CREATE TABLE skill_queue (INT id AUTO_INCREMENT PRIMARY KEY, VARCHAR(128) name);

CREATE TABLE header (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name);

CREATE TABLE honors (INT id AUTO_INCREMENT PRIMARY KEY, INT user_id, VARCHAR(128) name, VARCHAR(256) desc, VARCHAR location(128), INT(8) acquired);




